name: CI for our app using nodejs

on:
    pull_request:
        branches: ["development"]
    push:
        branches: ["development"]
    
jobs:
    test_pull_requests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
                run: npm ci --force
            - name: Build application
                env:
                    MONGODB_URI: ${{ secrets.MONGODB_URI }}
                    NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
                    NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                    GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                    DEFAULT_NEXTAUTH_URL: https://personal-dashboard-amber.vercel.app/
                run: |
                    if [ -z "$NEXTAUTH_URL" ]; then
                    export NEXTAUTH_URL=$DEFAULT_NEXTAUTH_URL
                    fi
                    echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env.local
                run: npm run build
            - name: Run tests
                env:
                    MONGODB_URI: ${{ secrets.MONGODB_URI }}
                    NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
                    NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                    GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                run: npm test


